### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by Greg-Boggs** [bbatsche/Ansible-Common-Role#1]
I tried using Base today because I tried to use your Nginx role and I got an error that www-group doesn't exist. So, I tried to add Base, and I got this error:

`
TASK [bbatsche.Base : Update APT] **********************************************
fatal: [128.199.246.116]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find aptitude. Please ensure it is installed."}
`

**Comment by bbatsche** [comment]
Hi Greg,

At this point in time, none of my roles have been validated against Ubuntu 16.04. I would very much like to support the LTS releases of Ubuntu but I have not had the time necessary to do that work. That said, this specific error points to `aptitude` not being installed on your server. You _may_ be able to work around this buy installing `aptitude` prior to running my role (either manually, by writing your own task to do so, or by including a different existing role). With that said, I make no guarantees that some other task(s) in this role won't also be broken.

Thank you for taking the time to submit these issues, and for investigating my Ansible roles.

**Comment by Greg-Boggs** [comment]
I hacked together a quick work around task. I believe all you need to do to support 16.04 is add this fix, and a python install. Everything else seems to have gone smoothly.

**Comment by bbatsche** [comment]
Excellent! Glad to hear you found a suitable work around. And I'll be sure to keep your advice in mind when I do manage to update these roles.
